import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        _id: uuid(),
        title: "Avocado Indian - 250 g",
        description: "Avocado is often eaten as a fruit eaten alone or mixed with other fruits in a fruit salad",
        img: "fruits/avocado.jpeg",
        category: "fruits",
        stock: "13",
        rating: "3.2",
        price: "207",
        currentPrice: "167",
        badge: {
            text: "Fresh Stock",
            color: "green"
        },
        tags: ["popular"]
    },
    {
        _id: uuid(),
        title: "Baby Corn - Exotic - 100 g",
        description: "Who can say no to baby corn? It is widely loved and used in many continental cuisines.",
        img: "vegetables/baby-corn.jpeg",
        category: "vegetables",
        stock: "0",
        rating: "3.9",
        price: "49",
        currentPrice: "37",
        badge: {
            text: "Fresh Stock",
            color: "green"
        },

    }, {
        _id: uuid(),
        title: "Broccoli - Exotic - 250 g",
        description: "Broccoli is classified in the Italica cultivar group of the species Brassica oleracea.",
        img: "vegetables/broccoli.jpeg",
        category: "vegetables",
        stock: "30",
        rating: "4.1",
        price: "51",
        tag: "populer",
        currentPrice: "37.5",
    }, {
        _id: uuid(),
        title: "Chilli green - 250 g",
        description: "Can we think of Indian cooking without a dash of hot, peppery green chillies?",
        img: "vegetables/Chilli-Green.jpeg",
        category: "vegetables",
        stock: "30",
        rating: "4.2",
        price: "35",
        currentPrice: "29",
        badge: {
            text: "Fresh Stock",
            color: "green"
        },
    },
    {
        _id: uuid(),
        title: "Brinjal Bharta - 500 g",
        description: "Avocado is often eaten as a fruit eaten alone or mixed with other fruits in a fruit salad",
        img: "vegetables/brinjal.png",
        category: "vegetables",
        stock: "10",
        rating: "4.5",
        price: "70",
        currentPrice: "59.5",
        badge: {
            text: "15% off",
            color: "yellow"
        },
    },
    {
        _id: uuid(),
        title: "Onion - 500 g",
        description: "Add sage and cheddar to make an extra special and delicious onion soup",
        img: "vegetables/onion.jpeg",
        category: "vegetables",
        stock: "12",
        rating: "2.3",
        price: "30",
        currentPrice: "26.9",
        badge: {
            text: "Fresh Stock",
            color: "green"
        },
    },
    {
        _id: uuid(),
        title: "Ginger - 100 g",
        description: "Steep a healing, rejuvenating cup of ginger tea on days when you need an extra push!",
        img: "vegetables/ginger.jpeg",
        category: "vegetables",
        stock: "22",
        rating: "4.5",
        price: "15",
        currentPrice: "7.9",
        badge: {
            text: "Fresh Stock",
            color: "green"
        },
    },
    {
        _id: uuid(),
        title: "Baby Potato - Exotic - 200 g",
        description: "Baby potatoes are smaller but have the exact same goodness as potatoes. They’re a roast favourite.",
        img: "vegetables/potato.jpeg",
        category: "vegetables",
        stock: "17",
        rating: "4.5",
        price: "25.8",
        currentPrice: "13",
        badge: {
            text: "Exotic",
            color: "red"
        },
    },
    {
        _id: uuid(),
        title: "Potato - 500 g",
        description: "Potato is a popular and important ingredient in every imaginable cuisine. It is loved globally.",
        img: "vegetables/potato-2.jpeg",
        category: "vegetables",
        stock: "22",
        rating: "4.5",
        price: "22",
        currentPrice: "17.6",
        badge: {
            text: "Fresh Stock",
            color: "green"
        },
    },
    {
        _id: uuid(),
        title: "Sprouts Green Peas 200 g",
        description: "Steep a healing, rejuvenating cup of ginger tea on days when you need an extra push!",
        img: "vegetables/SPROUTS-GREEN-PEAS.jpeg",
        category: "vegetables",
        stock: "27",
        rating: "4.1",
        price: "63",
        currentPrice: "49",
    },
    {
        _id: uuid(),
        title: "Tomato - 500 g",
        description: "Stuff tomatoes with some mixed veggies and crumbled panner and enjoy them grilled",
        img: "vegetables/tomato.jpeg",
        category: "vegetables",
        stock: "22",
        rating: "3.1",
        price: "35",
        currentPrice: "22.5",
        badge: {
            text: "Fresh Stock",
            color: "green"
        },
    },
    {
        _id: uuid(),
        title: "Tomato - Cherry Fresh Hydroponic - 250 g",
        description: "Stuff tomatoes with some mixed veggies and crumbled panner and enjoy them grilled",
        img: "vegetables/tomato-2.jpeg",
        category: "vegetables",
        stock: "11",
        rating: "3.1",
        price: "197",
        currentPrice: "169",
        badge: {
            text: "Exotic",
            color: "red"
        },
    },
    {
        _id: uuid(),
        title: "Strawberry - 250 g",
        description: "Who doesn't love fresh, red and juicy strawberries in this season, it's a delight to cherish these sweet sour tart snacks in the morning or even in the evening. Strawberries are an excellent source of vitamin C and healthy antioxidants that help lower the risk of heart problems and even control blood sugar levels. The ultimate satisfaction comes from eating fresh strawberries but they are immensely popular in their use for jams, jellies and desserts.",
        img: "fruits/strawberry_1.webp",
        category: "fruits",
        stock: "11",
        rating: "3.2",
        price: "145",
        currentPrice: "125",
        badge: {
            text: "Exotic",
            color: "red"
        },
    },
    {
        _id: uuid(),
        title: "Mandarin Orange - 250 g",
        description: "Luscious mandarin orange cake is a luxurious and appetizing indulgence!",
        img: "fruits/Mandarin-Orange.jpeg",
        category: "fruits",
        stock: "120",
        rating: "4.6",
        price: "128",
        currentPrice: "99.75",
        badge: {
            text: "fresh",
            color: "green"
        },
    },
    {
        _id: uuid(),
        title: "Apple New Zealand Rose - 500 g",
        description: "Here's the pefect rich and pulpy apples which are developed and bred in New Zealand.",
        img: "fruits/Apple-New-Zealand.jpeg",
        category: "fruits",
        stock: "20",
        rating: "3.3",
        price: "246",
        currentPrice: "199.5",
        badge: {
            text: "Exotic",
            color: "red"
        },
    },
    {
        _id: uuid(),
        title: "Apple Green - 500 g",
        description: "The compound quercitin, a major component in green apple peels, helps to lower sugar levels and manage type-2 diabetes mellitus.",
        img: "fruits/Apple-Green.jpeg",
        category: "fruits",
        stock: "30",
        rating: "3.8",
        price: "221",
        currentPrice: "169.5",
    },
    {
        _id: uuid(),
        title: "Banana Elaichi - 250 g",
        description: "Bananas can be eaten as a snack or paired with oatmeal or cereal for a power breakfast",
        img: "fruits/bannana.jpeg",
        category: "fruits",
        stock: "50",
        rating: "2.1",
        price: "45",
        currentPrice: "34.75",
        badge: {
            text: "22% off",
            color: "yellow"
        },
    },
    {
        _id: uuid(),
        title: "Musk Melon - 1 kg",
        description: "A delicious, refreshing juice made from musk melon is a summer favorite!",
        img: "fruits/Musk-Melon.jpeg",
        category: "fruits",
        stock: "10",
        rating: "4.1",
        price: "103",
        currentPrice: "79",
    },
    {
        _id: uuid(),
        title: "Pomegranate - 500 g",
        description: "Pomegranate is a round fruit with a thick, reddish maroon skin and hundreds of edible seeds within.",
        img: "fruits/Pomegranate.jpeg",
        category: "fruits",
        stock: "48",
        rating: "4.8",
        price: "227",
        currentPrice: "189",
        badge: {
            text: "fresh",
            color: "green"
        },
    },
    {
        _id: uuid(),
        title: "Guava - 250 g",
        description: "Besides its unique taste and smell, guava is appreciated as one of the super fruits!!",
        img: "fruits/Guava.jpeg",
        category: "fruits",
        stock: "28",
        rating: "3.7",
        price: "55",
        currentPrice: "33.75",
        badge: {
            text: "fresh",
            color: "green"
        },
    },
    {
        _id: uuid(),
        title: "Dragon Fruit - 500 g",
        description: "Its spongy pulp is white or sometimes pinkish red, sweet and juicy with numerous tiny edible black seeds scattered throughout.",
        img: "fruits/Dragon-Fruit.jpeg",
        category: "fruits",
        stock: "33",
        rating: "4",
        price: "199",
        currentPrice: "174.5",
        badge: {
            text: "12% off",
            color: "yellow"
        },
    },
    {
        _id: uuid(),
        title: "Pineapple - 1 kg",
        description: "Who does not like the juicy and zesty pineapple? This one is a must have.",
        img: "fruits/Pineapple.jpeg",
        category: "fruits",
        stock: "33",
        rating: "3.9",
        price: "129",
        currentPrice: "99",
    },
    {
        _id: uuid(),
        title: "Papaya - 1 kg",
        description: "Papaya is an almost staple fruit for all Indian families. It is loved for its digestive properties.",
        img: "fruits/Papaya.jpeg",
        category: "fruits",
        stock: "23",
        rating: "2.5",
        price: "72",
        currentPrice: "59",
    },
    {
        _id: uuid(),
        title: "Apricots Indian - 250 g",
        description: "Who does not like the juicy and zesty Apricots? This one is a must have.",
        img: "fruits/Apricots.jpeg",
        category: "fruits",
        stock: "69",
        rating: "4.1",
        price: "110.39",
        currentPrice: "87.59",
    },
    {
        _id: uuid(),
        title: "Plums Imported - 250 g",
        description: "The plum is a succulent fruit. Eaten globally, this red fruit can be consumed in multiple ways.",
        img: "fruits/Plums.jpeg",
        category: "fruits",
        stock: "43",
        rating: "4.4",
        price: "162",
        currentPrice: "124.75",
        badge: {
            text: "Exotic",
            color: "red"
        },
    },
    {
        _id: uuid(),
        title: "Organic Sorghum Flour - 50 g",
        description: "Sorghum is a broad term, referring to an entire group of grasses found in many tropical regions around the world – a group that has number of benefits that can improve your health. The cherry on the cake.",
        img: "groceries/Organic-Sorghum-Flour.jpeg",
        category: "groceries",
        stock: "43",
        rating: "3.4",
        price: "30",
        currentPrice: "23.1",
    },
    {
        _id: uuid(),
        title: "Organic Amaranth Flour - 50g",
        description: "Amaranth is considered a weed by most of the world, but it has been grown as a grain-like seed. One reason amaranth is emerging into the forefront among grains is because of its remarkable nutrition.",
        img: "groceries/Organic-Amaranth-Flour.jpeg",
        category: "groceries",
        stock: "43",
        rating: "4.4",
        price: "33",
        currentPrice: "27.35",
    },
    {
        _id: uuid(),
        title: "Organic Pearl Millet Flour (Bajra) - 50 g",
        description: "The most widely grown millet- The Pearl Millet, is known for its culinary uses as well as health benefits. Pearl millets, earlier known as ‘bird food’, come in several delicious flavors.",
        img: "groceries/Pearl-Millet-Flour.jpeg",
        category: "groceries",
        stock: "43",
        rating: "3.9",
        price: "40.2",
        currentPrice: "32.5",
    },
    {
        _id: uuid(),
        title: "Organic Ragi Flour - 50 g",
        description: "Ragi is one such super grain that has recently made a comeback. Popularly known as Finger Millet or Nachni in North India. Ragi flour is prepared by either crushing dried grains or spouting.",
        img: "groceries/Ragi-Flour.jpeg",
        category: "groceries",
        stock: "43",
        rating: "4.1",
        price: "35",
        currentPrice: "26.35",
    },
    {
        _id: uuid(),
        title: "NATURES KOLAM RICE - 1kg",
        description: "Ragi is one such super grain that has recently made a comeback. Popularly known as Finger Millet or Nachni in North India. Ragi flour is prepared by either crushing dried grains or spouting.",
        img: "groceries/KOLAM-RICE.jpeg",
        category: "groceries",
        stock: "43",
        rating: "4.1",
        price: "122",
        currentPrice: "99",
    },
    {
        _id: uuid(),
        title: "Peperomia Variegated - Medium",
        description: "If you love succulents, you will love the Peperomia Variegated. With its waxy and fleshy leaves and unique green and white variegations that change with time and light, it is good addition for tabletops or small spaces and its olive green leaves also provide good contrast. The peperomia needs very little help to make your space look lively.",
        img: "plants/Peperomia-Variegated copy.jpg",
        category: "plants",
        stock: "43",
        rating: "4.5",
        price: "745",
        currentPrice: "599",
    },
    {
        _id: uuid(),
        title: "Fittonia Green Plant (Nerve Plant)",
        description: "The Fittonia will satisfy the inner perfectionist in you. Each leaf of Fittonia Green is perfectly shaped with vivid white veins that run across the dark green leaf, earning it the names Nerve Plant and Silver Net Plant. She’s a temperamental plant, but totally worth the hassle!",
        img: "plants/fittoniagreennew_45 copy.jpg",
        category: "plants",
        stock: "43",
        rating: "4.1",
        price: "399",
        currentPrice: "299",
    },
    {
        _id: uuid(),
        title: "Spider Plant",
        description: "Chlorophytum Spider, also the Spider Plant is an impressive indoor plant and perfect for beginners. It is not only easy to care for but also a NASA certified air purifier. Its long, green foliage with white variegations look good in both hanging planters and as desktop setups. In favourable conditions, it blooms with small white flowers and its pups grow on stems cascading from the plant.",
        img: "plants/chlorophytumspider_45_1 copy.jpg",
        category: "plants",
        stock: "43",
        rating: "4.1",
        price: "369",
        currentPrice: "249",
    },
    {
        _id: uuid(),
        title: "Jade Plant Mini",
        description: "Are you a sucker for succulents? The Crassula Green Mini will be your dream plant kid. One of the easiest houseplants to look after, the Crassula Green Mini boasts a lush foliage which beautifies any room. Also considered lucky as per Feng Shui for its coin like round plump leaves, so go on, bring some green home, the luck just tags along for free.",
        img: "plants/crassulagreenmini_45.webp",
        category: "plants",
        stock: "43",
        rating: "4.1",
        price: "349",
        currentPrice: "249",
    },
    {
        _id: uuid(),
        title: "Money Plant Golden",
        description: "A darling of home gardeners everywhere, the Money Plant Golden is famous for its never give up attitude. This plant can survive neglect and adapt to almost all growing conditions to fill your space with a trailing growth of bright green coloured foliage in no time. An air purifier that can be styled for any space to give it an easy tropical look.",
        img: "plants/moneygolden_45_1 copy.jpg",
        category: "plants",
        stock: "43",
        rating: "4.3",
        price: "399",
        currentPrice: "349",
    },
    {
        _id: uuid(),
        title: "Philodendron Oxycardium Green Plant",
        description: "The indoor house plant that has been in trend for generations now, the Philodendron Oxycardium Green can as well be called the original superstar of the plant world. Large glossy heart shaped leaves, flexible trailing vines that can be styled as you wish and easy and quick growing nature make it a must have. Let it trail on your walls with the help of wire clips or a trellis – and voila, you have yourself a Pinterest worthy wall.",
        img: "plants/philodendronoxycardiumgreen_45_1 copy.jpg",
        category: "plants",
        stock: "43",
        rating: "4.3",
        price: "499",
        currentPrice: "449",
    },
    {
        _id: uuid(),
        title: "Ecor Spices Red Chilli Powder - 400 g",
        description: "HOMEMADE PURE JAIN SPICES, PROCESSING WITH TRADITIONAL MEHTODS - EXPLORING THE ORIGINAL TASTE OF MASALAS",
        img: "organic products/SPICES RED.jpeg",
        category: "organic products",
        stock: "43",
        rating: "4.3",
        price: "263",
        currentPrice: "205",
    },

];
